#test code
name: ui-actions

on:
    push:
        branch:
            - "main"
            - "master"
    pull_request:
        branch:
            - "main"
            - "master"

jobs:
    testing:
        runs-on: self-hosted

        steps:
            - name: step1
              uses: actions/checkout@v2
            - name: step2
              uses: actions/setup-node@v2
              with:
                node-version: 16.10
            - name: install deps
              run: npm ci
            - name: create build
              run: npm run build
            - name: remove build in backend server
              run: |
                    cd /home/ubuntu/backend/backend/newactions/newactions
                    find build/ && sudo rm -r build ||  
                    cd /home/ubuntu/frontEnd/frontEnd/action-frontEnd/action-frontEnd ; cp build/ /home/ubuntu/backend/backend/newactions/newactions
                # sudo rm -r build
                # cd /home/ubuntu/frontEnd/frontEnd/action-frontEnd/action-frontEnd
            # - name: move build to backend server
            #   run: cp -r build/ /home/ubuntu/backend/backend/newactions/newactions 
            - name: print number
              run: |
                 echo 20
                 echo 40+20
